---
- hosts: all
  become: yes
  tasks:

    - name: Install Nginx
      community.docker.docker_container:
        name: nginx
        image: nginx
        ports:
            - "80:80"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /opt/test-static/nginx/nginx.conf:/var/nginx/nginx.conf
          - /opt/test-static/nginx/conf.d/:/var/nginx/conf.d
          - /opt/test-static/public/:/var/test-static/public
        restart_policy: always