---
- hosts: all
  become: yes
  tasks:

    - name: Create PSSQL Container
      community.docker.docker_container:
        name: db_test
        image: "postgres:latest"
        ports:
            - "5432:5432"
        volumes:
            - db:/var/mysql

        restart_policy: always
        env:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"

